name: Pipeline DEV

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with: 
          java-version: 21
          distribution: 'temurin'
      - name: Cache Dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package
      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Login ECS Repository
        uses: docker/login-action@v3
        with: 
          registry: 549437042280.dkr.ecr.us-east-1.amazonaws.com/se-inscreve-no-canal
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build Docker Image
        run: docker build -t 549437042280.dkr.ecr.us-east-1.amazonaws.com/se-inscreve-no-canal:latest -t 549437042280.dkr.ecr.us-east-1.amazonaws.com/se-inscreve-no-canal:${{ github.sha }} .
      - name: Push Docker Image
        run: docker push --all-tags 549437042280.dkr.ecr.us-east-1.amazonaws.com/se-inscreve-no-canal
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: api/task-definition.json
  deploy-dev:
    needs: build
    name: Deploy Application DEV
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: artifact
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Update TaskDefinition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with: 
          task-definition: artifact/task-definition.json
          container-name: dev-container
          image: 549437042280.dkr.ecr.us-east-1.amazonaws.com/se-inscreve-no-canal:${{ github.sha }}
      - name: Deploy TaskDefinition to ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          cluster: dev-cluster
          service: dev-service
          wait-for-service-stability: true
          task-definition: ${{ steps.task-def.outputs.task-definition }}